### ISSUE TITLE
Refactor common code into base op mode

### ISSUE THREAD

**Issue by richiksc** [EdinaTerminators/terminator#27]
We need to refactor the common code in `AutonomousRed` and `AutonomousBlue` into the base opmode `ETBaseOpMode`. Right now, it's causing a lot of confusion for debugging and running, and we need to do the diff tool every time. This should make it easier.

@eku952 Can you work on this?

**Comment by eku952** [comment]
Issue Resolved

**Comment by eku952** [comment]
Issue Resolved
